project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"
    - "*.ipynb"
    - "!-*"
  resources:
    - "Posts/attachments"

website:
  title: "HST Research Blog"

  page-footer:
    border: true

  navbar: false

format:
  html:
    theme: cosmo
    number-sections: false
    css: styles.css
    toc: false
    highlight-style: github
