project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"
    - "*.ipynb"
    - "!-*"
  resources:
    - "Posts/attachments"

website:
  title: "HS Research Blog"

  page-footer:
    border: true

  navbar:
    left:
      - text: 신록예찬
        href: https://miruetoto.github.io/yechan/
    right:
      - icon: github
        href: https://github.com/miruetoto/hsblog

format:
  html:
    theme: cosmo
    number-sections: false
    css: styles.css
    toc: false
    highlight-style: github
